export const assets = {
    logo: 'assets/images/rahall-logo.svg',
    map: 'assets/images/map.png',
    ellipse: 'assets/images/Ellipse.png',
    van: 'assets/images/van.png',
    plane: 'assets/images/plane.png',
    ship: 'assets/images/ship.png',
    boxes: 'assets/images/boxes.png',
    arrow: 'assets/images/arrow.png',
    about: 'assets/images/Delivery-rahhal.png',
    service_1: 'assets/images/service-1.png',
    service_2: 'assets/images/service-2.png',
    service_3: 'assets/images/service-3.png',
    service_4: 'assets/images/service-4.png',
    service_5: 'assets/images/service-5.png',
    service_6: 'assets/images/service-6.png'
};

export const ServicesImage = {
    Service_img_01: 'assets/Services Image/Service-img-01.jpg',
    Service_img_02: 'assets/Services Image/Service-img-02.jpg',
    Service_img_03: 'assets/Services Image/Service-img-03.jpg',
    Service_img_04: 'assets/Services Image/Service-img-04.jpg',
    Service_img_05: 'assets/Services Image/Service-img-05.jpg',
    Service_img_06: 'assets/Services Image/Service-img-06.jpg',
    Service_img_07: 'assets/Services Image/Service-img-07.jpg',
    Service_img_08: 'assets/Services Image/Service-img-08.jpg',
    Service_img_09: 'assets/Services Image/Service-img-09.jpg',
    Service_img_10: 'assets/Services Image/Service-img-10.jpg',
    Service_img_11: 'assets/Services Image/Service-img-11.jpg',
    Service_img_12: 'assets/Services Image/Service-img-12.jpg',
    Service_img_13: 'assets/Services Image/Service-img-13.jpg',
    Service_img_14: 'assets/Services Image/Service-img-14.jpg',
    Service_img_15: 'assets/Services Image/Service-img-15.jpg',
    Service_img_16: 'assets/Services Image/Service-img-16.jpg',
    Service_img_17: 'assets/Services Image/Service-img-17.jpg',
    Service_img_18: 'assets/Services Image/Service-img-18.jpg',
    Service_img_19: 'assets/Services Image/Service-img-19.jpg',
    Service_img_20: 'assets/Services Image/Service-img-20.jpg',
    Service_img_21: 'assets/Services Image/Service-img-21.jpg',
    Service_img_22: 'assets/Services Image/Service-img-22.jpg',
    Service_img_23: 'assets/Services Image/Service-img-23.jpg',
    Service_img_24: 'assets/Services Image/Service-img-24.jpg',
    Service_img_25: 'assets/Services Image/Service-img-25.jpg',
    Service_img_26: 'assets/Services Image/Service-img-26.jpg',
    Service_img_27: 'assets/Services Image/Service-img-27.jpg',
    Service_img_28: 'assets/Services Image/Service-img-28.jpg',
    Service_img_29: 'assets/Services Image/Service-img-29.jpg',
    Service_img_30: 'assets/Services Image/Service-img-30.jpg',
    Service_img_31: 'assets/Services Image/Service-img-31.jpg',
    Service_img_32: 'assets/Services Image/Service-img-32.jpg',
    Service_img_33: 'assets/Services Image/Service-img-33.jpg',
    Service_img_34: 'assets/Services Image/Service-img-34.jpg',
    Service_img_35: 'assets/Services Image/Service-img-35.jpg',
    Service_img_36: 'assets/Services Image/Service-img-36.jpg',
    Service_img_37: 'assets/Services Image/Service-img-37.jpg',
    Service_img_38: 'assets/Services Image/Service-img-38.jpg',
    Service_img_39: 'assets/Services Image/Service-img-39.jpg',
    Service_img_40: 'assets/Services Image/Service-img-40.jpg',
    Service_img_41: 'assets/Services Image/Service-img-41.jpg'

};

export const ServicesVideo = {
    Video_01: 'assets/video/video-01.mp4',
    Video_02: 'assets/video/video-02.mp4',
    Video_03: 'assets/video/video-06.mp4',
    Video_04: 'assets/video/video-10.mp4',
    Video_05: 'assets/video/video-02.mp4',
    Video_06: 'assets/video/video-06.mp4',
    Video_07: 'assets/video/video-11.mp4',
    Video_08: 'assets/video/video-13.mp4',
    Video_09: 'assets/video/video-02.mp4',
    Video_10: 'assets/video/video-06.mp4',
    Video_11: 'assets/video/video-11.mp4',
    Video_12: 'assets/video/video-12.mp4',
    Video_13: 'assets/video/video-13.mp4',
}